apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['64.181.176.250:15692']