apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:management
          name: rabbitmq
          ports:
            - containerPort: 15672 
            - containerPort: 5672  
            - containerPort: 15692 
          env:
          - name: RABBITMQ_PROMETHEUS_EXCLUDE_QUEUE_METRICS
            value: "false"
          - name: RABBITMQ_PLUGINS
            value: "rabbitmq_management,rabbitmq_prometheus,rabbitmq_management_agent"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
    

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp 
      protocol: TCP
      port: 5672 
      targetPort: 5672 
    - name: management
      protocol: TCP
      port: 15672  
      targetPort: 15672 
    - name: prom
      protocol: TCP
      port: 15692
      targetPort: 15692